# Generated by Django 3.1.1 on 2021-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=25)),
                ('aadharPic', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('basicFlag', models.BooleanField()),
            ],
        ),
    ]
