# Generated by Django 3.1.1 on 2021-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210320_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.CharField(default='', max_length=250),
        ),
    ]
