# Generated by Django 3.1.1 on 2021-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('ngoid', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=15)),
                ('website', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=350)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('basicFlag', models.BooleanField()),
            ],
        ),
    ]
