# Generated by Django 3.1.1 on 2021-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='isGranted',
            field=models.BooleanField(null=True),
        ),
    ]
