# Generated by Django 3.1.1 on 2021-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210323_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='healthid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
