# Generated by Django 3.1.1 on 2021-03-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20210328_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patientname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
