# Generated by Django 3.1.1 on 2021-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_admission_patientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admitDate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
