# Generated by Django 3.1.1 on 2021-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_admission_dischargedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='billamt',
            field=models.CharField(default='', max_length=10),
        ),
    ]
