# Generated by Django 3.1.1 on 2021-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_admission_hospitalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='expense',
        ),
        migrations.AlterField(
            model_name='admission',
            name='billamt',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hospitalid',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='patientid',
            field=models.IntegerField(max_length=50),
        ),
    ]
