# Generated by Django 3.1.1 on 2021-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20210329_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='billamt',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
