# Generated by Django 3.1.1 on 2021-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20210329_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('hospitalid', models.IntegerField()),
                ('ngoid', models.IntegerField()),
                ('admissionid', models.IntegerField()),
                ('isapproved', models.BooleanField(null=True)),
                ('approvedamt', models.FloatField()),
            ],
        ),
    ]
