# Generated by Django 3.1.1 on 2021-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='ngoname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='requestdate',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='requestedamt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='responsedate',
            field=models.CharField(default='', max_length=25),
        ),
    ]
