# Generated by Django 3.1.1 on 2021-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20210401_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='approvedamt',
            field=models.FloatField(default=0),
        ),
    ]
