# Generated by Django 3.1.1 on 2021-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_auto_20210401_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='pendingbillamt',
            field=models.FloatField(default=0),
        ),
    ]
