# Generated by Django 3.1.1 on 2021-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_admission_pendingbillamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionid', models.IntegerField()),
                ('billamt', models.FloatField(default=0, max_length=10)),
                ('billpaid', models.BooleanField(default=False)),
                ('pendingbillamt', models.FloatField(default=0)),
                ('billImg', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
