# Generated by Django 3.1.1 on 2021-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='timeofBillAddition',
            field=models.CharField(default='', max_length=50),
        ),
    ]
