# Generated by Django 3.1.1 on 2021-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_bill_timeofbilladdition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billDesc',
            field=models.CharField(default='', max_length=350),
        ),
    ]
