# Generated by Django 3.1.1 on 2021-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_bill_billdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='requestdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='responsedate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
